### ISSUE TITLE
homey app validate/publish command failed

### ISSUE THREAD

**Issue by fiLLLip** [athombv/node-athom-cli#150]
Not sure if this is the right place to address this, but I got an error after trying to use the `homey` cli since the old upload of apps is removed. I tried publish, validate, and nothing works.

`$ homey app validate
✓ Pre-processing app...
✓ Running plugins...
✓ Running plugin `zwave`...
✓ Installing homey-meshdriver@latest...
Trace: Error: Command failed: npm install homey-meshdriver@latest  --save

    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  killed: false,
  code: 243,
  signal: null,
  cmd: 'npm install homey-meshdriver@latest  --save'
}
    at App.preprocess (/usr/local/lib/node_modules/homey/node_modules/athom-cli/lib/App/index.js:209:17)
Trace: Plugin `zwave` did not finish:
Command failed: npm install homey-meshdriver@latest  --save

Aborting.
    at Object.exports.handler (/usr/local/lib/node_modules/homey/node_modules/athom-cli/bin/cmds/app/validate.js:26:11)
`

**Comment by RobinBol** [comment]
Could you run `npm install -g homey@beta` to verify whether this issue still persists?

To be honest, I believe you have a permissions issue on your system, check these resources to fix that:
- https://github.com/infinitered/ignite/issues/246
- https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally
