### ISSUE TITLE
Support for Node 6.x runtime

### ISSUE THREAD

**Issue by BasKiers** [athombv/node-athom-cli#20]
Upgrading to Node.js 6.x resulted in the following error 

```
(node:2728) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
C:\Users\Bas\AppData\Roaming\npm\node_modules\athom-cli\node_modules\observed\lib\observed.js:77
  Object.observe(this.subject, this.onchange);
         ^

TypeError: Object.observe is not a function
    at Observable._bind (C:\Users\Bas\AppData\Roaming\npm\node_modules\athom-cli\node_modules\observed\lib\observed.js:77:10)
    at new Observable (C:\Users\Bas\AppData\Roaming\npm\node_modules\athom-cli\node_modules\observed\lib\observed.js:41:8)
    at Observable (C:\Users\Bas\AppData\Roaming\npm\node_modules\athom-cli\node_modules\observed\lib\observed.js:36:12)
    at module.exports (C:\Users\Bas\AppData\Roaming\npm\node_modules\athom-cli\node_modules\jsop\index.js:13:14)
    at Object.<anonymous> (C:\Users\Bas\AppData\Roaming\npm\node_modules\athom-cli\lib\settings.js:10:19)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

**Comment by matjaz** [comment]
Object.observe is removed. see https://github.com/aheckmann/observed
jsop should be updated.
